title: Ingrid Nkenlifack # your name (or website title) here
logo: "/images/Ingrid_Nken_cropped_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi I'm Ingrid. I'm an college student getting my Bachelors in Information Systems in 2021, and I'm into data science and software development. I enjoy analyzing data with Python and creating Android mobile applications on the side. Come check out my work<br><br>
  Class of 2021, UMBC 
  <br><br>
  <a href="https://www.linkedin.com/in/ingridn/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-177762987-1 # your Google Analytics tracking ID here
